### PR TITLE
sync the change

### PR DESCRIPTION
**Pull request by coiby**

### CODE REVIEW

**Comment by coiby** [comment]
Hi David @dashea,

This is Coiby and I'm the current maintainer of kdump-anaconda-addon. My team wants to put this repo under https://github.com/rhinstaller/. Can you merge this PR and transfer the project to rhinstaller? I have to bother you because forked project i.e. daveyoung/kdump-anaconda-addon can't be transferred.

**Comment by dashea** [comment]
@coiby I merged the change, but I don't have permission to create repositories under rhinstaller anymore. You'll need to fork it to the organization.

**Comment by VladimirSlavik** [comment]
@dashea perhaps something could be arranged with @jkonecny12 ?

**Comment by coiby** [comment]
> 

@dashea Thanks for merging the code! In fact, github doesn't provide a way to transfer a forked repository to another account. But you as the creator of the repo can transfer the repository to rhinstaller:) I've already discussed this issue with @jkonecny12 and he's happy to have this project under rhinstaller GH organization.

**Comment by jkonecny12** [comment]
I wonder @dashea do you need permissions on the rhinstaller org or are you just able to change the maintainer to someone else?

**Comment by daveyoung** [comment]
I think no need to bother @dashea,  I have initiated transferring the kdump addon to rhinstaller org,  it may need approval by the owner of rhinstaller.

**Pull request merged**
